spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    
logging:
  file:
    name: library
    path: ./logs
    max-size: 10MB
    max-history: 7
  level:
    root: info
  config: classpath:logback-spring.xml